sonar.projectKey=habituo-web
sonar.organization=Habituo
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.token=squ_8a2b68df8fc80f5ebfd28f2eadea64da4e768bf2
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js,**/*.test.jsx,**/*.spec.jsx