export { default as Home } from "../pages/Home";
export { default as Contact } from "../pages/Contact";
export { default as About } from "../pages/About";
export { default as Dashboard } from "../pages/dashboard/Dashboard";
export { default as DashboardHome } from "../pages/dashboard/DashboardHome";
export { default as AllAreas } from "../pages/dashboard/sections/AllAreas";
export { default as AllHabits } from "../pages/dashboard/sections/AllHabits";
export { default as TodoList } from "../pages/dashboard/home/TodoList";
export { default as TimeTracker } from "../pages/dashboard/home/TimeTracker";
export { default as ActivityTracker } from "../pages/dashboard/home/ActivityTracker";
export { default as AllContent } from "../pages/dashboard/home/AllContent";
export { default as AreaPage } from "../pages/dashboard/areas/AreaPage";
export { default as HabitPage } from "../pages/dashboard/habits/HabitPage";
export { default as Login } from "../pages/authentication/Login";
export { default as Register } from "../pages/authentication/Register";
export { default as RecoverPassword } from "../pages/authentication/RecoverPassword";
export { default as UserProfileSection } from "../pages/authentication/UserProfileSection";
export { default as EmailVerified } from "../pages/authentication/EmailVerified";
export { default as CustomThemePanel } from "../theme/CustomThemePanel";
export { default as Navbar } from "../components/Navbar";
export { default as Footer } from "../components/Footer";
export { default as AreaCard } from "../components/AreaCard";
export { default as HabitCard } from "../components/HabitCard";
export { default as ConfirmationModal } from "../components/ConfirmationModal";
export { default as NoDataPage } from "../components/NoDataPage";
export { default as ColumnHeader } from "../pages/dashboard/sections/ColumnHeader";
export { default as LeftColumn } from "../pages/dashboard/sections/LeftColumn";
export { default as ModalArea } from "../components/ModalArea";
export { default as ModalHabit } from "../components/ModalHabit";
export { default as VerifyEmailButton } from "../components/VerifyEmailButton";
export { default as LegalContent} from "../pages/policies/LegalContent";
export { default as PrivacyPolicy} from "../pages/policies/content/PrivacyPolicy";
export { default as LegalTerms} from "../pages/policies/content/LegalTerms";
export { default as CookiesBanner} from "../pages/policies/CookiesBanner";
