export * from "./components/layout";
export * from "./components/modals";
export * from "./components/ui";
export * from "./sections";
export { default as BarChart } from "./components/charts/BarChart";
export { default as ColumnHeader } from "./components/dashboard/ColumnHeader";
export { default as DashboardHeader } from "./components/dashboard/DashboardHeader";

export { default as CustomThemePanel } from "./components/theme/CustomThemePanel";

export { default as HomePage } from "./pages/HomePage/HomePage";
export { default as AboutPage } from "./pages/AboutPage";
export { default as ContactPage } from "./pages/ContactPage";
export { default as EmailVerifiedPage } from "./pages/auth/EmailVerifiedPage";
export { default as LoginPage } from "./pages/auth/LoginPage";
export { default as RegisterPage } from "./pages/auth/RegisterPage";
export { default as RecoverPasswordPage } from "./pages/auth/RecoverPasswordPage";
export { default as UserProfileSection } from "./pages/auth/UserProfileSection";
export { default as DashboardLayout } from "./pages/dashboard/DashboardLayout";
export { default as DashboardHomePage } from "./pages/dashboard/DashboardHomePage";
export { default as AreaDetailPage } from "./pages/areas/AreaDetailPage";
export { default as AllAreasPage } from "./pages/areas/AllAreasPage";
export { default as HabitDetailPage } from "./pages/habits/HabitDetailPage";
export { default as AllHabitsPage } from "./pages/habits/AllHabitsPage";
export { default as ActivityTrackerPage } from "./pages/home/ActivityTrackerPage";
export { default as AllContentPage } from "./pages/home/AllContentPage";
export { default as TimeTrackerPage } from "./pages/home/TimeTrackerPage";
export { default as TodoListPage } from "./pages/home/TodoListPage";
export { default as LegalContentLayout } from "./pages/legal/LegalContentLayout";
export { default as LegalTermsPage } from "./pages/legal/LegalTermsPage";
export { default as PrivacyPolicyPage } from "./pages/legal/PrivacyPolicyPage";
